basePath: /
definitions:
  models.DriverLicence:
    properties:
      address:
        type: string
      birth_date:
        type: string
      category:
        type: string
      expiration_date:
        type: string
      father_name:
        type: string
      first_name:
        type: string
      id:
        type: string
      issue_date:
        type: string
      issued_by:
        type: string
      last_name:
        type: string
      licence_number:
        type: string
    type: object
  models.Error:
    properties:
      error:
        type: string
    type: object
  models.Fine:
    properties:
      fine_date:
        type: string
      fine_owner:
        type: string
      id:
        type: string
      license_plate:
        type: string
      officer_id:
        type: string
      payment_date:
        type: string
      price:
        type: integer
      tech_passport_number:
        type: string
    type: object
  models.FineAccept:
    properties:
      id:
        type: string
    type: object
  models.FineReq:
    properties:
      fine_date:
        type: string
      fine_owner:
        type: string
      license_plate:
        type: string
      officer_id:
        type: string
      payment_date:
        type: string
      price:
        type: integer
      tech_passport_number:
        type: string
    type: object
  models.LicenceNumber:
    properties:
      number:
        type: string
      userId:
        type: string
    type: object
  models.LoginEmailRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.LoginResponse:
    properties:
      id:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
  models.Message:
    properties:
      message:
        type: string
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
  models.Service:
    properties:
      address:
        type: string
      certificate_number:
        type: string
      id:
        type: string
      manager_name:
        type: string
      name:
        type: string
      phone_number:
        type: string
      type:
        type: string
    type: object
  models.Services:
    properties:
      services:
        items:
          $ref: '#/definitions/models.Service'
        type: array
    type: object
  models.Tokens:
    properties:
      access_token:
        type: string
      data:
        $ref: '#/definitions/models.LoginResponse'
      refresh_token:
        type: string
    type: object
  models.UpdateCarImage:
    properties:
      url:
        type: string
      user_id:
        type: string
    type: object
  models.Url:
    properties:
      url:
        type: string
    type: object
  models.UserFines:
    properties:
      car_owner_name:
        type: string
      licence_plate:
        type: string
      officer_id:
        type: string
    type: object
  models.UserProfile:
    properties:
      created_at:
        type: string
      driver_license:
        $ref: '#/definitions/models.DriverLicence'
      email:
        type: string
      role:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
  description: Server for signIn or signUp
  title: Authentication service
  version: "1.0"
paths:
  /auth/add_license:
    post:
      consumes:
      - application/json
      description: Add a new license to the system
      parameters:
      - description: License information
        in: body
        name: License
        required: true
        schema:
          $ref: '#/definitions/models.LicenceNumber'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Add a new license
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: sign in user
      parameters:
      - description: register user
        in: body
        name: LoginEmail
        required: true
        schema:
          $ref: '#/definitions/models.LoginEmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Tokens'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: LoginEmail Users
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: create users
      parameters:
      - description: register user
        in: body
        name: Register
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Register Users
      tags:
      - Auth
  /fines:
    get:
      consumes:
      - application/json
      description: Retrieve all fines
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of records per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Fine'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Get All Fines
      tags:
      - Fines
    post:
      consumes:
      - application/json
      description: Create a new fine
      parameters:
      - description: Create fine
        in: body
        name: Fine
        required: true
        schema:
          $ref: '#/definitions/models.FineReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Create Fines
      tags:
      - Fines
  /fines/{id}/accept:
    put:
      consumes:
      - application/json
      description: Accept a fine by updating its payment date
      parameters:
      - description: Fine ID
        in: path
        name: id
        required: true
        type: integer
      - description: Accept fine
        in: body
        name: FineAccept
        required: true
        schema:
          $ref: '#/definitions/models.FineAccept'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Accept Fines By ID
      tags:
      - Fines
  /fines/paid:
    get:
      consumes:
      - application/json
      description: Retrieve all paid fines
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Fine'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Get Paid Fines
      tags:
      - Fines
  /fines/unpaid:
    get:
      consumes:
      - application/json
      description: Retrieve all unpaid fines
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Fine'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Get Unpaid Fines
      tags:
      - Fines
  /service:
    get:
      consumes:
      - application/json
      description: Get all services
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Services'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get all services
      tags:
      - service
  /service/{id}:
    get:
      consumes:
      - application/json
      description: Get service
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Service'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get service
      tags:
      - service
  /service/create:
    post:
      consumes:
      - application/json
      description: Create service
      parameters:
      - description: service
        in: body
        name: service
        required: true
        schema:
          $ref: '#/definitions/models.Service'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Service'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create service
      tags:
      - service
  /service/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Delete service
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Delete service
      tags:
      - service
  /service/update:
    put:
      consumes:
      - application/json
      description: Update service
      parameters:
      - description: service
        in: body
        name: service
        required: true
        schema:
          $ref: '#/definitions/models.Service'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Service'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Update service
      tags:
      - service
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Delete User
      tags:
      - User
  /user/image:
    post:
      consumes:
      - application/json
      description: Upload a new car image
      parameters:
      - description: Car Image
        in: body
        name: image
        required: true
        schema:
          $ref: '#/definitions/models.UpdateCarImage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Add Car Image
      tags:
      - User
  /user/image/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve the image of a user's car
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Url'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Get Car Image
      tags:
      - User
  /user/paid_fines/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve all paid fines for a user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.UserFines'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Get Paid Fines
      tags:
      - User
  /user/profile/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve the profile of a user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserProfile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Get User Profile
      tags:
      - User
  /user/unpaid_fines/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve all unpaid fines for a user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.UserFines'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Get Unpaid Fines
      tags:
      - User
schemes:
- http
swagger: "2.0"
