version: "3.9"

services:
  migrate:
    image: "migrate/migrate"
    networks:
      - road
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:123321@postgres:5432/road_24?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123321
      - POSTGRES_DB=road_24
    networks:
      - road
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  serv:
    container_name: road24
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - road
    ports:
      - "8080:8080"
networks:
  road:
    name: road
    driver: bridge

volumes:
  postgres_data:
  migrations: